# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-20 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='URL')),
                ('author', models.CharField(blank=True, max_length=256, null=True, verbose_name='auth.User')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('published', models.BooleanField(default=True, verbose_name='Released')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Column_name')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='Column_url')),
                ('intro', models.TextField(default='', verbose_name='Section_profile')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Column',
                'verbose_name_plural': 'Column',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ManyToManyField(to='news.Column', verbose_name='Attribution_columns'),
        ),
    ]
