# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-21 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181121_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=models.CharField(max_length=256, unique=True, verbose_name='类别网址'),
        ),
    ]
